root:
  - ./*

rest: 
  - src/controllers

documentation:
  - docs/*
  
framework:
  - src/main/*
  
javascript:
  - **/*.js
  
typescript:
  - **/*.ts
  
Event:
  - src/events/*
 
Command: 
  - src/commands/*


  
